# action on push to main

name:  Deploy-To-Server

on:
 push:
   branches: 
     - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Start 
      run: | 
        scp -o StrictHostKeyChecking=no -r ./index.html user1@34.28.128.248:/var/www/html
  
